FROM golang:1.20 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY *.go ./

RUN go run main.go migrate:seed

RUN CGO_ENABLED=0 GOOS=linux go build -o /web3

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /web3 /web3

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/web3"]