version: "3.9"

services:
  database:
    image: "mysql:latest"
    env_file:
      - .env_file
    container_name: "web3-mysql"
    ports:
      - 3306:3306
    networks:
      - sis_network
  web3:
    build: .
    container_name: "web3"
    networks:
      - sis_network
networks:
  sis_network:
    driver: bridge